language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
before_install:
    - composer self-update

install:
    - composer update --no-interaction

script:
    - vendor/bin/phpunit --coverage-text
